[package]
name = "hook0-client"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
lazy-regex = "3.2.0"
log = "0.4.22"
reqwest = { version = "0.12.5", default-features = false, features = ["hickory-dns", "json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
thiserror = "1.0.63"
url = "2.5.2"
uuid = { version = "1.10.0", features = ["serde", "v4"] }

[features]
default = ["reqwest-rustls-tls-webpki-roots"]
reqwest-rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots"]
reqwest-rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots"]
